### PR TITLE
Split deployment into two instances with nginx running on top and

### PR DESCRIPTION
**Pull request by hategan**
added customization to each.

This is basically to support two separate instance of the testing service for PSI/J and the SDK.

### CODE REVIEW

**Comment by zekemorton** [comment]
This looks really good! I took a look at the Nginx configuration, deployment, build and service files and everything seems solid to me. My key take aways from this are:
1. The Nginx configuration was moved to VM instead of the container, and routes to the two containers via ports 9901 to psi/j and 9902 to sdk 
2. Both the sdk and psi/j containers use the exact same image, they just mount different volumes for the mongodb and for the web customizations in the deployment.
I also tried accessing this to test it out at sdk.testing.exaworks.org, but it doesn't look like its running. Is there a specific way to view/test changes?

**Comment by zekemorton** [comment]
This looks really good! I took a look at the Nginx configuration, deployment, build and service files and everything seems solid to me. My key take aways from this are:
1. The Nginx configuration was moved to VM instead of the container, and routes to the two containers via ports 9901 to psi/j and 9902 to sdk 
2. Both the sdk and psi/j containers use the exact same image, they just mount different volumes for the mongodb and for the web customizations in the deployment.
I also tried accessing this to test it out at sdk.testing.exaworks.org, but it doesn't look like its running. Is there a specific way to view/test changes?

**Comment by hategan** [comment]
> Is there a specific way to view/test changes?

I tested it locally, on ubuntu 20.04, like this:
- `SERVICE_VERSION=0.1.11` in config (this probably only matters for docker image builds)
- if you do want to test docker image builds, then:
    - `IMAGE=<something_you_have_access_to_on_docker_hub>` in config
    - `cd docker`
    - `./build.sh`
- `DEV=1` in config
- put an SSL certificate for `*.testing.exaworks.org` in `/etc/ssl/exaworks/{certs|private}/ssl.{crt|key}`; you can generate  a self signed one and then you'll have to wrestle with your browser
- `cd deploy`
-  `sudo ./deploy.sh`. Make sure you are not running apache or another web server. This *will* install nginx and run it on whatever you are running this on. 
- make sure `testing.exaworks.org`, `psij.testing.exaworks.org`, and `sdk.testing.exaworks.org` point to 127.0.0.1

**Comment by zekemorton** [comment]
I'll go ahead and approve this now because it looks good to me, but it might be worth having at least one other person take a look!

**Comment by zekemorton** [comment]
I'll go ahead and approve this now because it looks good to me, but it might be worth having at least one other person take a look!

**Review by zekemorton — APPROVED** [review]
LGTM

**Review by zekemorton — APPROVED** [review]

**Comment by zekemorton** [comment]
@hategan Looks like my approval doesn't work because I don't have write access. 
`At least 1 approving review is required by reviewers with write access.`

**Comment by hategan** [comment]
I added you to the project.

I'll merge it myself. I have a few last minute updates to make.

**Pull request merged**
